services:

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  fastapi:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env.docker
