name: Tests and Checks

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  tests-and-checks:
    name: Run checks and tests

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: fastapi
          POSTGRES_PASSWORD: fastapi
          POSTGRES_DB: fastapi
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DOMAIN: localhost
      PROJECT_NAME: FastAPI
      FIRST_SUPERUSER: fastapi
      FIRST_SUPERUSER_PASSWORD: fastapi
      ENVIRONMENT: local
      SECRET_KEY: insecure-secret-key
      POSTGRES_SERVER: localhost
      POSTGRES_DB: fastapi
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install requirements
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Run pre-commit hook
        uses: pre-commit/action@v3.0.1

      - name: Run migrations
        run: |
          alembic upgrade head
        env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Run Pytest suite
        run: |
          pytest --disable-warnings tests/
        env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
